### ISSUE TITLE
Meta-Issue: Reencryption

### ISSUE THREAD

**Issue by MaximilianKrambach** [MaximilianKrambach/enigmail_fork#1]
This is a meta issue, Upstream of enigmail is at sourceforge.

I am probably doing something wrong with git, so proper credits will not always be given. Features desired are:

- [ ]  Reencryption: Branch encryptFilter_reencryption. Encrypt encrypted messages with new key.
- [ ] Filter action to encrypt: Branch encryptFilter_reencryptionFilter based on encryptFilter_reencryption.
- [ ] Account reencryption: offer to reencrypt all encrypted messages of the account if the account's key changes.
- [ ] filterTermEncrypted: A filter condition applied if the email is encrypted.
